### ISSUE TITLE
Retrieve data from all cars in the session

### ISSUE THREAD

**Issue by JLEGit** [gotzl/pyacc#1]
I create this issue to answer a question, how to retrieve the best laps, etc... of each car in the session?

**Comment by gotzl** [comment]
The purpose of this repo is only to read the ACC shared memory. This shared memory does not contain detailed information of all cars in the session, as one can also see in the [docu](https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/).

I think there was once a API for spectators which might give you the information you seek. But I don't know if this API still exists or if there are tools to easily access this information ...
